---
# Site information
site_name: vaxflux Documentation
site_url: https://accidda.github.io/vaxflux/

# Repository information
repo_name: ACCIDDA/vaxflux
repo_url: https://github.com/ACCIDDA/vaxflux
edit_uri: ''

# Theme information and customization
theme:
  name: material
  custom_dir: overrides
  features:
    - content.code.copy

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css

# Plugins
plugins:
  - search
  - autorefs
  - mkdocs-jupyter:
      execute: false
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_full_path: false
            merge_init_into_class: true
            heading_level: 2

# Extras
extra:
  version:
    provider: mike

# Markdown extensions
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# Navigation structure
nav:
  - Home: index.md
  - Introduction: introduction.md
  - Installation: installation.md
  - Getting Started: getting-started.md
  - Model Details: model-details.md
  - Demos:
      - Season Only Vaxflux Model: demos/season-only-vaxflux-model.ipynb
      - Vaxflux Model: demos/vaxflux-model.ipynb
      - NIS-FRVM Survey: demos/nis-frvm-survey.ipynb
  - API Reference:
      - Vaxflux: api/vaxflux.md
      - Data: api/data.md
  - Contributing: contributing.md
  - Changelog: changelog.md
