[tool.poetry]
name = "vaxflux"
version = "0.1.0"
description = ""
authors = ["Timothy Willard <9395586+TimothyWillard@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
numpy = ">=1.17.0,<2"
pymc = "^5.16.2"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"


[tool.poetry.group.demo.dependencies]
matplotlib = "^3.9.2"
seaborn = "^0.13.2"
arviz = "^0.19.0"
ipykernel = "^6.29.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
