name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.10'
          - '3.11'
          - '3.12'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup pandoc for docs
        uses: r-lib/actions/setup-pandoc@v2
      - name: Setup uv with python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: 'pyproject.toml'
          python-version: ${{ matrix.python-version }}
      - name: Run Checks
        run: make ci
        env:
          UV_PYTHON_VERSION: ${{ matrix.python-version }}
