name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.10'
          - '3.11'
          - '3.12'
          # - '3.13' # Temporarily disabled due to numpy not having pre-built wheels
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup uv with python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: 'pyproject.toml'
          python-version: ${{ matrix.python-version }}
      - name: Install package and dependencies
        run: |
          uv sync --all-extras
          uv pip install -e .
      - name: Check formatting/linting with ruff
        run: |
          uv run ruff format --check
          uv run ruff check --no-fix
      - name: Check types with mypy
        run: uv run mypy --python-version ${{ matrix.python-version }} .
      - name: Run unit tests with pytest
        run: uv run pytest --exitfirst
