---
name: 'GitHub Pages Deploy'

'on':
  push:
    branches:
      - 'main'
  release:
    types:
      - 'published'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: 'read'

jobs:
  deploy:
    name: 'deploy'
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        python-version:
          - '3.12'
    permissions:
      contents: 'write' # Needed to push to gh-pages
    steps:
      - name: 'checkout repository'
        uses: 'actions/checkout@v5'
        with:
          ref: 'main'
      - name: 'setup just'
        uses: 'extractions/setup-just@v3'
      - name: 'setup uv with python ${{ matrix.python-version }}'
        uses: 'astral-sh/setup-uv@v7'
        with:
          enable-cache: true
          cache-dependency-glob: 'pyproject.toml'
          python-version: '${{ matrix.python-version }}'
      - name: 'fetch gh-pages branch'
        run: |
          git fetch origin gh-pages:gh-pages --depth=1
          git config --global user.name "${ACTOR}"
          git config --global user.email "${ACTOR}@users.noreply.github.com"
        env:
          ACTOR: '${{ github.actor }}'
      - name: 'extract version'
        id: extract-version
        run: |
          cat > version.py << EOF
          import tomllib
          with open('pyproject.toml', 'rb') as f:
              data = tomllib.load(f)
          version = data['project']['version']
          version = '.'.join(version.split('.')[:2])
          print(f"version={version}")
          EOF
          uv run -qq python version.py >> $GITHUB_OUTPUT
          rm version.py
      - name: 'build docs'
        run: 'just docs'
      - name: 'Deploy to GitHub Pages'
        run: |
          uv run mike set-default latest
          if [ "${EVENT_NAME}" == "release" ] || [[ $VERSION == 0* ]]; then
            ALIAS=latest
          else
            ALIAS=dev
          fi
          uv run mike deploy \
            --push --update-aliases \
            ${VERSION} ${ALIAS}
        env:
          EVENT_NAME: '${{ github.event_name }}'
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          VERSION: '${{ steps.extract-version.outputs.version }}'
