---
name: 'lint'

'on':
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  prettier:
    name: 'prettier'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'setup just'
        uses: 'extractions/setup-just@v3'
      - name: 'checkout repository'
        uses: 'actions/checkout@v5'
      - name: 'setup node'
        uses: 'actions/setup-node@v6'
        with:
          node-version: 'latest'
          cache-dependency-path: 'package-lock.json'
      - name: 'prettier check'
        run: 'just prettier-check'
  cspell:
    name: 'cspell'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'setup just'
        uses: 'extractions/setup-just@v3'
      - name: 'checkout repository'
        uses: 'actions/checkout@v5'
      - name: 'setup node'
        uses: 'actions/setup-node@v6'
        with:
          node-version: 'latest'
          cache-dependency-path: 'package-lock.json'
      - name: 'cspell check'
        run: 'just cspell'
  yamllint:
    name: 'yamllint'
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        python-version:
          - '3.12'
    steps:
      - name: 'setup just'
        uses: 'extractions/setup-just@v3'
      - name: 'checkout repository'
        uses: 'actions/checkout@v5'
      - name: 'setup uv'
        uses: 'astral-sh/setup-uv@v6'
        with:
          enable-cache: true
          cache-dependency-glob: 'pyproject.toml'
          python-version: '${{ matrix.python-version }}'
      - name: 'yamllint check'
        run: 'just yamllint'
        env:
          UV_PYTHON_VERSION: '${{ matrix.python-version }}'
