---
name: 'Lint'

'on':
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

permissions:
  contents: 'read'

jobs:
  prettier:
    name: 'prettier'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'checkout repository'
        uses: 'actions/checkout@v6.0.2'
      - name: 'setup just'
        uses: 'extractions/setup-just@v4'
      - name: 'setup node'
        uses: 'actions/setup-node@v6.4.0'
        with:
          node-version: 'latest'
          cache-dependency-path: 'package-lock.json'
      - name: 'prettier check'
        run: 'just prettier-check'
  cspell:
    name: 'cspell'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'checkout repository'
        uses: 'actions/checkout@v6.0.2'
      - name: 'setup just'
        uses: 'extractions/setup-just@v4'
      - name: 'setup node'
        uses: 'actions/setup-node@v6.4.0'
        with:
          node-version: 'latest'
          cache-dependency-path: 'package-lock.json'
      - name: 'cspell check'
        run: 'just cspell'
  yamllint:
    name: 'yamllint'
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        python-version:
          - '3.14'
    steps:
      - name: 'checkout repository'
        uses: 'actions/checkout@v6.0.2'
      - name: 'setup just and uv'
        uses: './.github/actions/setup-just-and-uv'
        with:
          python-version: '${{ matrix.python-version }}'
      - name: 'yamllint check'
        run: 'just yamllint'
        env:
          UV_PYTHON_VERSION: '${{ matrix.python-version }}'
